language: php

php:
  - 5.4
  - 5.5

before_script:
  - sudo apt-get install vsftpd
  - sudo sed -i s/#anonymous_enable=YES/anonymous_enable=YES/g /etc/vsftpd.conf
  - sudo sed -i s/#anon_upload_enable=YES/anon_upload_enable=YES/g /etc/vsftpd.conf
  - sudo sed -i s/#anon_mkdir_write_enable=YES/anon_mkdir_write_enable=YES/g /etc/vsftpd.conf
  - sudo mkdir /ftp
  - sudo usermod -d /ftp ftp
  - sudo service vsftpd restart
  - cat /etc/vsftpd.conf